detectors:
  UtilityFunction:
    exclude:
      - 'options'
      - 'FileHelper'
      - 'ApiWrapper'
  IrresponsibleModule:
    exclude:
      - 'MenuSection'
      - 'FeatureHelper'
  DuplicateMethodCall:
    exclude:
      - 'register_user'
  Attribute:
    enabled: false
  TooManyStatements:
    max_statements: 15
  TooManyInstanceVariables:
    max_instance_variables: 6
  FeatureEnvy:
    exclude:
      - 'ApiWrapper'